name: DevOps Masterclass Pipeline

on:
  push:

jobs:

  terraform:
    name: Terraform Kickoff
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    outputs:
      ec2_public_ip: ${{ steps.terraform_output.outputs.public_ip }}

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Get EC2 Public IP
        id: terraform_output
        run: |
          echo "public_ip=$(terraform output -raw public_ip)" >> $GITHUB_OUTPUT

  ansible:
    name: Ansible Kickoff
    needs: terraform
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create PEM File
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 400 private_key.pem

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install ansible -y

      - name: Create Inventory File
        run: |
          echo "[dev]" > inventory.ini
          echo "${{ needs.terraform.outputs.ec2_public_ip }} ansible_user=ec2-user ansible_ssh_private_key_file=private_key.pem" >> inventory.ini

      - name: Install Python on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@${{ needs.terraform.outputs.ec2_public_ip }} "sudo yum install python -y"

      - name: Run Ansible Playbook
        run: |
          ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i inventory.ini ansible/setup.yaml